# Generated by Django 4.2 on 2025-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_aceess',
        ),
        migrations.AddField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
