# Generated by Django 4.2 on 2025-08-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='created_at',
            new_name='content_type',
        ),
    ]
